### ISSUE TITLE
CensoredASM has a rendering conflict with Optifine

### ISSUE THREAD

**Issue by Overjay** [Red-Studio-Ragnarok/Opticraft#6] opened 2023-07-10 17:55 UTC
So, both CensoredASM and Optifine have this function where they won't render animated texture, such as fire, if it is not in FOV. 

If you run CensoredASM with factory settings AND Optifine in one pack - some animated textures will not be animated. In my modpack this cancels animation of regular fire, blue fire from BoP and nether portal animation.

To "fix" the issue one has to set "onDemandAnimatedTextures=false" in CensoredASM config.

I think this issue and its solution can be mentioned on the page, or elsewhere.

Thank you for your tremendous work in creating this compendium!

**Comment by Desoroxxx** [comment] 2023-07-17 02:20
It think it is better to wait for them to fix it, as this is a minor issue with an easy fix.
Currently Opticraft is sadly not built for adding the solutions to problems.

I think the issue is already fixed for CensoredASM V6 anyway.

Will keep this issue open though

*Note: Sorry for the extremely late reply, I just realized that GitHub stopped automatically watching my repo's orgs, so I was never notified of this. *

**Comment by Desoroxxx** [comment] 2023-10-10 11:20
I will close this for now as it is either already fixed or will be fixed in V6

**Closed by Desoroxxx** 2023-10-10 11:20 UTC
